"""
Per-cell runner for the Myriad (SGE) finite-size scaling sweep.

One SGE array task = one (N, r) cell. The task id comes from
SGE_TASK_ID (1-based) and maps to a cell via scripts/sweep_params.txt
(generated by scripts/make_sweep_params.py). Trajectories within the
cell are parallelised across the task's allocated cores (NSLOTS).

PHYSICS (unchanged, called as-is):
  - trajectory pathway identical to scripts/run_sweep_v2_i3.py: fully
    seed-deterministic (numpy-seeded structure, Cliffords numpy-
    indexed into the cached 2-qubit Clifford group, seeded
    TableauSimulator). The 2-qubit Clifford cache helper is
    self-contained here because the published all_to_all_stim.py does
    not export it.
  - S_R via src/analysis/entropy_fast.reference_entropy_fast — the
    EXISTING bit-packed exact path, previously verified bit-identical
    to entropy.py:stabiliser_entropy_region (300 random matrices +
    240 checks on evolving tableaux). Chosen because the old python
    path costs ~20-30 s PER ENTROPY CALL at N=1024, which would
    threaten the wall-time; the fast path gives the same integers in
    ~0.3 s. No file in src/ is modified.

SEEDING (kept EXACTLY as the old script for consistency with existing
data): seed(N, r, j) = (N*1000 + round(100 r)) * 100000 + j.
Documented wart: on this sweep's 0.005 grid, half-step rates share a
seed BASE with a neighbouring rate (round(100*0.305) = 30 =
round(100*0.300) under banker's rounding), so the RNG streams of some
adjacent cells are coupled. Within-cell statistics and bootstraps are
unaffected; cross-cell coupling is mild and noted rather than "fixed",
because changing the formula would break seed-compatibility with the
existing outputs_v2 data on the 0.01 grid.

SAMPLE SCHEDULE: the old script's approach scaled to the per-size
depth — make_sample_times(depth_factor*N, n_log=14, n_lin=10).

PER-SIZE DEPTH AND TRAJECTORIES (finite-size scaling design: small
sizes need longer relative depth and more trajectories):
    N     : 64  96  128 192 256 384 512 768 1024
    depth : 48N 40N 32N 28N 20N 16N 14N 12N 12N
    n_traj: 120 120 100 80  60  50  50  50  50

STORAGE (same keys as the old script, so existing analysis reads it):
  cell_N{N}_r{r:.4f}.npz with sr (n_traj, n_times) raw bits, seeds,
  meas_counts, times — plus additive metadata keys: depth_factor,
  convergence_residual (relative fall of mean S_R/N over the final
  20% of the run; target <= 2% near the transition), and
  n_monotonicity_warnings. Atomic write (tmp+rename); cells whose
  output exists are skipped, so a resubmitted array resumes.

TEST MODE: TEST_TRAJ=<k> in the environment caps trajectories at k
and redirects output to <outdir>/test/ so test cells can never be
mistaken for complete production cells.

Output root: ~/Scratch/outputs_scaling (override with OUTDIR env or
--outdir). Raw cells land in <root>/raw/.

Usage (normally invoked by the jobscript):
    PYTHONPATH=. python scripts/run_cell_myriad.py
"""

# Imports
import json
import os
import sys
import time
from multiprocessing import Pool

import numpy as np

from src.simulators.all_to_all_stim import make_sample_times
from src.analysis.entropy_fast import reference_entropy_fast

DEPTH_FACTOR = {64: 48, 96: 40, 128: 32, 192: 28, 256: 20,
                384: 16, 512: 14, 768: 12, 1024: 12}
N_TRAJ = {64: 120, 96: 120, 128: 100, 192: 80, 256: 60,
          384: 50, 512: 50, 768: 50, 1024: 50}
N_LOG, N_LIN = 14, 10                    # old script's schedule

_CLIFFORD_CACHE = None


def _two_qubit_cliffords():
    """All 11,520 two-qubit Cliffords, enumerated once per worker."""
    global _CLIFFORD_CACHE
    if _CLIFFORD_CACHE is None:
        import stim
        _CLIFFORD_CACHE = tuple(stim.Tableau.iter_all(2))
    return _CLIFFORD_CACHE


def cell_seed(N, r, j):
    # EXACT old-script formula — see module docstring for the
    # documented half-step base-sharing on the 0.005 grid.
    return (N * 1000 + int(round(100 * r))) * 100000 + j


def run_one(args):
    """One trajectory: (S_R(t) raw bits, meas_count, seed, n_warn)."""
    N, r, seed, t_max = args
    import stim
    times = make_sample_times(t_max, N_LOG, N_LIN)
    rng = np.random.default_rng(seed)
    cliffords = _two_qubit_cliffords()
    sim = stim.TableauSimulator(seed=seed)
    sim.set_num_qubits(2 * N)
    for i in range(N):
        sim.h(N + i)
        sim.cnot(N + i, i)
    sample_set = set(times)
    idx_of = {t: i for i, t in enumerate(times)}
    sr = np.full(len(times), np.nan)
    meas_count = 0
    for step in range(1, t_max + 1):
        for _ in range(N):
            if rng.random() < r:
                q = int(rng.integers(0, N))
                sim.measure(q)
                meas_count += 1
            else:
                a = int(rng.integers(0, N))
                b = int(rng.integers(0, N - 1))
                if b >= a:
                    b += 1
                c = int(rng.integers(0, len(cliffords)))
                sim.do_tableau(cliffords[c], [a, b])
        if step in sample_set:
            sr[idx_of[step]] = reference_entropy_fast(sim, N)
    n_warn = int(np.sum(np.diff(sr) > 1e-9))
    return sr, meas_count, seed, n_warn


def main():
    # ---- resolve the cell from SGE_TASK_ID ---------------------------
    tid = os.environ.get("SGE_TASK_ID")
    if tid is None or tid == "undefined":
        sys.exit("SGE_TASK_ID not set — this script is meant to run "
                 "as an SGE array task (or set it manually).")
    tid = int(tid)
    params_path = os.path.join(os.path.dirname(__file__),
                               "sweep_params.txt")
    cell = None
    with open(params_path) as f:
        for line in f:
            t, n_s, r_s = line.split()
            if int(t) == tid:
                cell = (int(n_s), float(r_s))
                break
    if cell is None:
        sys.exit(f"task id {tid} not found in {params_path}")
    N, r = cell

    depth = DEPTH_FACTOR[N]
    t_max = depth * N
    n_traj = N_TRAJ[N]
    test_traj = os.environ.get("TEST_TRAJ")
    outroot = os.environ.get(
        "OUTDIR", os.path.expanduser("~/Scratch/outputs_scaling"))
    if len(sys.argv) > 2 and sys.argv[1] == "--outdir":
        outroot = sys.argv[2]
    if test_traj:
        n_traj = min(n_traj, int(test_traj))
        outroot = os.path.join(outroot, "test")
    outdir = os.path.join(outroot, "raw")
    os.makedirs(outdir, exist_ok=True)

    key = f"N{N}_r{r:.4f}"
    path = os.path.join(outdir, f"cell_{key}.npz")
    if os.path.exists(path):
        print(f"[skip] task {tid} {key}: output exists", flush=True)
        return

    nslots = int(os.environ.get("NSLOTS", "2"))
    print(f"[start] task {tid}: {key}, depth {depth}N (t_max={t_max}),"
          f" {n_traj} trajectories on {nslots} cores", flush=True)

    times = make_sample_times(t_max, N_LOG, N_LIN)
    t0 = time.time()
    jobs = [(N, r, cell_seed(N, r, j), t_max) for j in range(n_traj)]
    sr = np.zeros((n_traj, len(times)))
    seeds = np.zeros(n_traj, dtype=np.int64)
    mcounts = np.zeros(n_traj, dtype=np.int64)
    warns = 0
    with Pool(nslots) as pool:
        for k, (s, mc, sd, nw) in enumerate(
                pool.imap(run_one, jobs, chunksize=1)):
            sr[k], mcounts[k], seeds[k] = s, mc, sd
            warns += nw
            if (k + 1) % 10 == 0:
                print(f"  {k + 1}/{n_traj} trajectories "
                      f"[{(time.time()-t0)/60:.1f} min]", flush=True)

    # ---- convergence check: relative fall over the final 20% ---------
    t_arr = np.array(times, dtype=float)
    mean_curve = sr.mean(axis=0) / N
    k80 = int(np.argmin(np.abs(t_arr - 0.8 * t_max)))
    s80, s_end = mean_curve[k80], mean_curve[-1]
    residual = float((s80 - s_end) / s80) if s80 > 1e-12 else 0.0

    tmp = path + ".tmp.npz"
    np.savez_compressed(
        tmp, sr=sr, seeds=seeds, meas_counts=mcounts,
        times=np.array(times), depth_factor=depth,
        convergence_residual=residual,
        n_monotonicity_warnings=warns)
    os.replace(tmp, path)

    if warns:
        print(f"[WARNING] {key}: {warns} S_R increases detected",
              flush=True)
    flag = "" if residual <= 0.02 else "  <-- ABOVE 2% TARGET"
    print(f"[done] task {tid} {key}: {(time.time()-t0)/60:.1f} min, "
          f"convergence residual {residual*100:.2f}%{flag}",
          flush=True)


if __name__ == "__main__":
    main()
